// MV3 service worker (non-module) compatible script
// Listens for messages via chrome.runtime.onMessage and replies with analysis result.
// Add startup logging and global error handlers to aid debugging when the SW fails to register.

try {
  // Log early so extension inspector shows the worker loaded
  console.log('Smart Highlights service worker: init');
} catch (e) {
  // ignore in environments where console may be restricted
}

// Capture runtime errors to console so developer can inspect failures in SW evaluation
try {
  if (typeof self !== 'undefined' && self.addEventListener) {
    self.addEventListener('error', (ev) => {
      try {
        console.error('Smart Highlights service worker error:', ev && ev.message ? ev.message : ev);
      } catch (e) {
        // ignore
      }
    });
  }
} catch (e) {
  // ignore
}

// Helper to read backend URL from storage; returns default if not set
function getBackendUrl(defaultUrl = 'http://localhost:8080/analyze') {
  return new Promise((resolve) => {
    try {
      chrome.storage && chrome.storage.local
        ? chrome.storage.local.get(['backendUrl'], (items) => {
            resolve(items && items.backendUrl ? items.backendUrl : defaultUrl);
          })
        : resolve(defaultUrl);
    } catch (e) {
      resolve(defaultUrl);
    }
  });
}

// Perform the POST to backend and return normalized response object
async function postAnalyze(url, text, timeout = 5000) {
  const controller = typeof AbortController !== 'undefined' ? new AbortController() : null;
  const timer = controller ? setTimeout(() => controller.abort(), timeout) : null;
  try {
    const res = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
      body: JSON.stringify({ text }),
      signal: controller ? controller.signal : undefined,
    });
    if (timer) clearTimeout(timer);
    const json = await res.json().catch(() => null);
    return { ok: !!res.ok, status: res.status || null, result: json };
  } catch (err) {
    if (timer) clearTimeout(timer);
    return { ok: false, error: err ? String(err.message || err) : 'unknown' };
  }
}

// Helper: check if devMode flag is set in storage
function getDevMode() {
  return new Promise((resolve) => {
    try {
      if (typeof chrome !== 'undefined' && chrome.storage && chrome.storage.local) {
        chrome.storage.local.get(['devMode'], (items) => {
          resolve(!!(items && items.devMode));
        });
      } else {
        resolve(false);
      }
    } catch (e) {
      resolve(false);
    }
  });
}
// Exported onMessage handler to make the logic testable in Node.
// Accepts either an event-like object { data: { type, text, timeout } } or direct payload.
async function onMessage(eventOrPayload) {
  const payload = eventOrPayload && eventOrPayload.data ? eventOrPayload.data : eventOrPayload || {};
  if (!payload || payload.type !== 'analyze') {
    return { ok: false, error: 'unsupported' };
  }
  const backendUrl = await getBackendUrl();
  const timeout = payload.timeout || 5000;
  // Dev-mode: if requested by payload or enabled via storage, return a mock response immediately
  try {
    const devMode = await getDevMode();
    if (payload && (payload.mock === true || devMode)) {
      const text = payload.text || '';
      const mockResult = {
        ok: true,
        status: 200,
        result: {
          summary: `MOCK summary for: ${String(text).slice(0, 120)}`,
          explanation: 'This is a developer-mode mock response generated by the extension.',
          translation: null,
          dev: true,
        },
      };
      return mockResult;
    }
  } catch (e) {
    // ignore and continue to real backend
  }
  // Prefer project's requestAnalysis if available (makes unit tests mockable).
  // In test/Node environments (no chrome), prefer importing the project's requestAnalysis
  if (typeof chrome === 'undefined') {
    try {
      const mod = await import('../lib/request.js');
      if (mod && typeof mod.requestAnalysis === 'function') {
        const resp = await mod.requestAnalysis(payload.text, { timeout });
        return resp;
      }
    } catch (e) {
      // ignore and fall back to fetch
    }
  }

  const res = await postAnalyze(backendUrl, payload.text, timeout);
  return res;
}

// If running in the real extension context, register the chrome.runtime listener.
try {
  if (typeof chrome !== 'undefined' && chrome.runtime && chrome.runtime.onMessage) {
    console.log('Smart Highlights service worker: registering onMessage listener');
    // mark worker ready in storage so other extension pages can know when it's safe to send messages
    try {
      if (chrome && chrome.storage && chrome.storage.local) {
        chrome.storage.local.set({ swReady: true, swReadyAt: Date.now() }, () => {
          try {
            console.log('Smart Highlights service worker: swReady flag set');
          } catch (e) {}
        });
      }
    } catch (e) {
      // ignore
    }
    chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
      try {
        console.log('Smart Highlights service worker: incoming message', message);
      } catch (e) {
        // ignore
      }
      (async () => {
        const res = await onMessage(message);
        sendResponse(res);
      })();
      return true; // indicate async reply
    });
  }
} catch (e) {
  try {
    console.error('Error during service worker listener registration', e && e.message ? e.message : e);
  } catch (err) {
    // ignore
  }
}

// Export for tests in CommonJS environments (guarded)
try {
  // @ts-ignore
  module.exports = { onMessage };
} catch (e) {
  // ignore in browser/service worker
}

// Optional: handle install/update events for debugging (guard for Node tests)
if (typeof self !== 'undefined' && self.addEventListener) {
  self.addEventListener('activate', (ev) => {
    // keep worker alive briefly for debugging
    // console.log('Smart Highlights service worker activated');
  });
}
