#!/usr/bin/env bash
# Create GitHub issues from specs/001-create-a-full/tasks.md
# Supports: gh CLI or GitHub REST API with GH_TOKEN
# Usage: ./create_github_issues.sh [--dry-run] [--create] [--assignee username]

set -euo pipefail
FEATURE_DIR=$(dirname "$0")
TASKS_MD="$FEATURE_DIR/tasks.md"
DRY_RUN=true
DO_CREATE=false
ASSIGNEE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=true; shift ;;
    --create) DO_CREATE=true; DRY_RUN=false; shift ;;
    --assignee) ASSIGNEE="$2"; shift 2 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

if [[ ! -f "$TASKS_MD" ]]; then
  echo "tasks.md not found at $TASKS_MD" >&2
  exit 1
fi

# Determine creation method
USE_GH_CLI=false
USE_API=false
if command -v gh >/dev/null 2>&1; then
  USE_GH_CLI=true
elif [[ -n "${GH_TOKEN:-}" ]]; then
  USE_API=true
else
  USE_GH_CLI=false
  USE_API=false
fi

repo_full=""
if $USE_API; then
  # derive owner/repo from git remote
  remote_url=$(git remote get-url origin 2>/dev/null || true)
  if [[ -z "$remote_url" ]]; then
    echo "GH_TOKEN provided but git remote 'origin' not found; cannot determine repo" >&2
    exit 1
  fi
  # convert git@github.com:owner/repo.git or https://github.com/owner/repo.git to owner/repo
  repo_full=$(echo "$remote_url" | sed -E 's#git@github.com:(.*)\.git#\1#; s#https://github.com/(.*)\.git#\1#')
fi

current_title=""
current_body=""
issue_count=0

flush_issue() {
  if [[ -z "$current_title" ]]; then
    return
  fi
  issue_count=$((issue_count+1))
  echo "Prepared Issue $issue_count: $current_title"
  if $DRY_RUN; then
    echo "---"
    echo "$current_title"
    echo
    echo "$current_body"
    echo "---\n"
    return
  fi

  body_payload="$current_body\n\n_From tasks.md generated by create_github_issues.sh_"

  if $USE_GH_CLI; then
    cmd=(gh issue create --title "$current_title" --body "$body_payload" --label "feature")
    if [[ -n "$ASSIGNEE" ]]; then
      cmd+=(--assignee "$ASSIGNEE")
    fi
    "${cmd[@]}"
  elif $USE_API; then
    json_body=$(printf '{"title": %s, "body": %s, "labels": ["feature"]' "$(jq -R -s '.' <<< "$current_title")" "$(jq -R -s '.' <<< "$body_payload")")
    if [[ -n "$ASSIGNEE" ]]; then
      json_body+=$(printf ', "assignees": [%s]' "$(jq -R -s '.' <<< "$ASSIGNEE")")
    fi
    json_body+=('}')

    curl -s -X POST "https://api.github.com/repos/$repo_full/issues" \
      -H "Authorization: token $GH_TOKEN" \
      -H "Accept: application/vnd.github.v3+json" \
      -d "$json_body"
  else
    echo "No creation method available (install gh CLI or set GH_TOKEN)." >&2
    exit 1
  fi
}

while IFS= read -r line || [[ -n "$line" ]]; do
  if [[ "$line" =~ ^T[0-9]+ ]]; then
    flush_issue
    current_title="$line"
    current_body=""
  else
    current_body+="$line\n"
  fi
done < "$TASKS_MD"

# flush last
flush_issue

echo "Done. $issue_count issues processed."
