#!/usr/bin/env bash
# Create GitHub issues from specs/001-create-a-full/tasks.md using the `gh` CLI
# Usage: ./create_github_issues.sh [--dry-run] [--assignee username]

set -euo pipefail
FEATURE_DIR=$(dirname "$0")
TASKS_MD="$FEATURE_DIR/tasks.md"
DRY_RUN=false
ASSIGNEE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=true; shift ;;
    --assignee) ASSIGNEE="$2"; shift 2 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

if [[ ! -f "$TASKS_MD" ]]; then
  echo "tasks.md not found at $TASKS_MD" >&2
  exit 1
fi

current_title=""
current_body=""
issue_count=0

while IFS= read -r line; do
  if [[ "$line" =~ ^T[0-9]+ ]]; then
    # flush previous
    if [[ -n "$current_title" ]]; then
      issue_count=$((issue_count+1))
      echo "Issue $issue_count: $current_title"
      if [[ "$DRY_RUN" == false ]]; then
        body="$current_body\n\n_From tasks.md generated by create_github_issues.sh_"
        cmd=(gh issue create --title "$current_title" --body "$body" --label "feature" )
        if [[ -n "$ASSIGNEE" ]]; then
          cmd+=(--assignee "$ASSIGNEE")
        fi
        "${cmd[@]}"
      fi
    fi
    # start new issue
    current_title="$line"
    current_body=""
  else
    current_body+="$line\n"
  fi
done < "$TASKS_MD"

# flush last
if [[ -n "$current_title" ]]; then
  issue_count=$((issue_count+1))
  echo "Issue $issue_count: $current_title"
  if [[ "$DRY_RUN" == false ]]; then
    body="$current_body\n\n_From tasks.md generated by create_github_issues.sh_"
    cmd=(gh issue create --title "$current_title" --body "$body" --label "feature" )
    if [[ -n "$ASSIGNEE" ]]; then
      cmd+=(--assignee "$ASSIGNEE")
    fi
    "${cmd[@]}"
  fi
fi

echo "Done. $issue_count issues processed."
